/* =========================================================================
   ملف اللغات — Snake 2048
   - I18N: ترجمات نصوص الواجهة + التعليمات (جدول مبسّط بالأيقونات).
   - LANGS: قائمة لغات كبيرة قابلة للبحث؛ غير المترجَمة تعود للإنجليزية.
   ========================================================================= */

window.I18N = {
  en: { _name: "English", stats: "Your Stats", best: "Top", score: "Score", length: "Length", time: "Time", high: "Best", level: "Stage", leaderboard: "Leaders", play: "Play", online: "Play Online", join: "Join", joinTitle: "Join with a code", joinPh: "Paste room code", paste: "Paste", install: "📲 Install app", roomCode: "Room code — send to friends", roomShort: "Room", copy: "Copy", gameOver: "Game Over", winner: "Winner", winNote: "🎁 Prize: 3 double charges — tap or press E", restart: "Restart", solo: "Solo", multi: "Multiplayer", lock: "Public / Private", namePh: "Enter your name", you: "You", search: "Search language…", joined: "joined", left: "left", hostNow: "You are the host now", mapNext: "Next map — Stage", roomNotFound: "Room not found", connecting: "Connecting…", copied: "Copied ✓", paused: "Paused", resume: "Resume", exit: "Exit to menu", help: "How to play", howTitle: "How to Play", close: "Close", hIdea: "The idea", hIdeaTxt: "Eat cubes ≤ your head. Equal numbers merge (2,4,8…). Avoid edges & red zones.", hModes: "Modes", mPublic: "Public", mPrivate: "Private", hControls: "Controls", hPowers: "Power-ups", cSteer: "Steer", cBoost: "Boost", cPause: "Pause", cEmoji: "Emoji", cCharge: "Charge", pSpeed: "Speed", pDouble: "Double", pHalf: "Half", pRadar: "Radar", hInstall: "Install", hInstallTxt: "Tap the game icon at the top of the menu to install it as an app. iPhone: Share → Add to Home Screen.", hSolo: "👤 Eat cubes whose number is equal to or smaller than your head to grow. When two equal numbers touch, they merge into the next number (2 becomes 4, then 8, and so on), so your snake gets longer and its head number rises.", hMulti: "👥 You can eat other players to grow. You may bite any part of a rival's body as long as that part's number is smaller than your head. If you eat the rival's head, that player loses and leaves the game.", hAvoid: "Avoid the map edges, because leaving the map means instant death, and stay away from the red danger zones.", pSpeedTxt: "Speed boost for 3s.", pDoubleTxt: "Doubles all your numbers.", pHalfTxt: "Halves your numbers (a 2 vanishes).", pRadarTxt: "Reveals the nearest players for 8s.", pDanger: "Danger", pDangerTxt: "Red zone — drops your cubes one by one; if only the head is left, you lose.", installHint: "Open the browser menu → \"Add to Home Screen\"", netTimeout: "Couldn't reach the server — check your internet and try again.", netGlobal: "Global (Internet)", netLocal: "Local (Wi‑Fi)", netNeedInternet: "Global mode needs an internet connection.", shape: "Shape", aiEnemies: "AI Enemies" },

  ar: { _name: "العربية", _rtl: 1, stats: "إحصائياتك", best: "أعلى رقم", score: "النقاط", length: "الطول", time: "الوقت", high: "الأفضل", level: "المرحلة", leaderboard: "المتصدّرون", play: "ابدأ اللعب", online: "العب أونلاين", join: "انضمام", joinTitle: "انضمام برمز صديق", joinPh: "الصق رمز الغرفة", paste: "لصق", install: "📲 ثبّت التطبيق", roomCode: "رمز الغرفة — أرسله لأصدقائك", roomShort: "رمز الغرفة", copy: "نسخ", gameOver: "انتهت اللعبة", winner: "المنتصر", winNote: "🎁 الجائزة: 3 شحنات مضاعفة — انقرها أو اضغط E", restart: "إعادة اللعب", solo: "فردي", multi: "جماعي", lock: "عامة / خاصة", namePh: "اكتب اسمك", you: "أنت", search: "ابحث عن لغة…", joined: "انضم", left: "غادر", hostNow: "أنت المضيف الآن", mapNext: "الخريطة التالية — المرحلة", roomNotFound: "الغرفة غير موجودة", connecting: "جارٍ الاتصال…", copied: "نُسخ ✓", paused: "إيقاف مؤقت", resume: "استئناف", exit: "الخروج للقائمة", help: "كيف تلعب", howTitle: "كيف تلعب", close: "إغلاق", hIdea: "الفكرة", hIdeaTxt: "كُل المكعبات ≤ رأسك. الأرقام المتساوية تندمج (2،4،8…). تجنّب الحدود والمناطق الحمراء.", hModes: "الأوضاع", mPublic: "عامة", mPrivate: "خاصة", hControls: "التحكّم", hPowers: "القوى", cSteer: "توجيه", cBoost: "تسارع", cPause: "إيقاف", cEmoji: "رموز", cCharge: "شحنة", pSpeed: "سرعة", pDouble: "مضاعفة", pHalf: "نصف", pRadar: "رادار", hInstall: "تثبيت", hInstallTxt: "انقر أيقونة اللعبة أعلى المنيو لتثبيتها كتطبيق. آيفون: مشاركة ← إضافة للشاشة الرئيسية.", hSolo: "👤 كُل المكعبات التي رقمها مساوٍ أو أصغر من رقم رأسك لتكبر. وعندما يتلامس رقمان متساويان يندمجان في الرقم التالي (الاثنان يصيران أربعة، ثم ثمانية، وهكذا)، فيطول ثعبانك ويعلو رقم رأسه.", hMulti: "👥 يمكنك أكل اللاعبين الآخرين لتكبر. ويمكنك أن تعضّ أيّ جزء من جسد المنافس ما دام رقم ذلك الجزء أصغر من رقم رأسك. وإذا أكلت رأس المنافس فإنه يخسر ويخرج من اللعبة.", hAvoid: "تجنّب حدود الخريطة لأنّ الخروج منها يعني الموت فوراً، وابتعد عن المناطق الحمراء الخطرة.", pSpeedTxt: "اندفاع سرعة لمدة 3 ثوانٍ.", pDoubleTxt: "يضاعف كل أرقامك.", pHalfTxt: "يقسم أرقامك على 2 (الرقم 2 يختفي).", pRadarTxt: "يكشف أقرب اللاعبين لمدة 8 ثوانٍ.", pDanger: "خطر", pDangerTxt: "منطقة حمراء — تُسقط مكعباتك واحداً تلو الآخر؛ وإن بقي الرأس فقط تخسر.", installHint: "افتح قائمة المتصفح ← \"إضافة إلى الشاشة الرئيسية\"", netTimeout: "تعذّر الوصول للخادم — تحقّق من الإنترنت وحاول ثانية.", netGlobal: "عالمي (إنترنت)", netLocal: "محلي (واي‑فاي)", netNeedInternet: "الوضع العالمي يتطلّب اتصالاً بالإنترنت.", shape: "الشكل", aiEnemies: "أعداء AI" },

  es: { _name: "Español", stats: "Tus estadísticas", best: "Máx", score: "Puntos", length: "Largo", time: "Tiempo", high: "Récord", level: "Nivel", leaderboard: "Líderes", play: "Jugar", online: "Jugar en línea", join: "Unirse", joinTitle: "Unirse con código", joinPh: "Pega el código", paste: "Pegar", install: "📲 Instalar app", roomCode: "Código de sala — compártelo", roomShort: "Sala", copy: "Copiar código", gameOver: "Fin del juego", winner: "Ganador", winNote: "🎁 Premio: 3 cargas dobles — toca o pulsa E", restart: "Reiniciar", solo: "Individual", multi: "Multijugador", lock: "Pública / Privada", namePh: "Tu nombre", you: "Tú", search: "Buscar idioma…", joined: "se unió", left: "salió", hostNow: "Ahora eres el anfitrión", mapNext: "Siguiente mapa — Nivel", roomNotFound: "Sala no encontrada", connecting: "Conectando…", copied: "Copiado ✓", paused: "Pausa", resume: "Reanudar", exit: "Salir al menú", help: "Cómo jugar", howTitle: "Cómo jugar", close: "Cerrar", hIdea: "La idea", hIdeaTxt: "Come cubos ≤ tu cabeza. Iguales se fusionan (2,4,8…). Evita bordes y zonas rojas.", hModes: "Modos", mPublic: "Pública", mPrivate: "Privada", hControls: "Controles", hPowers: "Mejoras", cSteer: "Dirigir", cBoost: "Impulso", cPause: "Pausa", cEmoji: "Emoji", cCharge: "Carga", pSpeed: "Velocidad", pDouble: "Doble", pHalf: "Mitad", pRadar: "Radar", hInstall: "Instalar", hInstallTxt: "Toca el icono del juego arriba del menú para instalarlo. iPhone: Compartir → Añadir a pantalla de inicio.", shape: "Forma", hSolo: "👤 Come cubos cuyo número sea igual o menor que tu cabeza para crecer. Cuando dos números iguales se tocan, se fusionan en el siguiente (el 2 pasa a 4, luego 8, etc.), así tu serpiente crece y su cabeza sube.", hMulti: "👥 Puedes comer a otros jugadores para crecer. Muerde cualquier parte del cuerpo de un rival cuyo número sea menor que tu cabeza. Si comes la cabeza del rival, ese jugador pierde y sale.", hAvoid: "Evita los bordes del mapa, salir es muerte instantánea, y aléjate de las zonas rojas peligrosas.", pSpeedTxt: "Impulso de velocidad por 3s.", pDoubleTxt: "Duplica todos tus números.", pHalfTxt: "Divide tus números a la mitad (el 2 desaparece).", pRadarTxt: "Muestra los jugadores cercanos por 8s.", pDanger: "Peligro", pDangerTxt: "Zona roja — suelta tus cubos uno a uno; si solo queda la cabeza, pierdes.", installHint: "Abre el menú del navegador → \"Añadir a pantalla de inicio\"", netTimeout: "No se pudo conectar al servidor — revisa tu internet e inténtalo de nuevo.", netGlobal: "Global (Internet)", netLocal: "Local (Wi‑Fi)", netNeedInternet: "El modo global necesita conexión a internet." },

  fr: { _name: "Français", stats: "Tes stats", best: "Max", score: "Score", length: "Longueur", time: "Temps", high: "Record", level: "Niveau", leaderboard: "Classement", play: "Jouer", online: "Jouer en ligne", join: "Rejoindre", joinTitle: "Rejoindre via un code", joinPh: "Collez le code", paste: "Coller", install: "📲 Installer l'app", roomCode: "Code de salon — à partager", roomShort: "Salon", copy: "Copier le code", gameOver: "Partie terminée", winner: "Gagnant", winNote: "🎁 Prix : 3 charges doubles — touchez ou E", restart: "Rejouer", solo: "Solo", multi: "Multijoueur", lock: "Public / Privé", namePh: "Votre nom", you: "Toi", search: "Chercher une langue…", joined: "a rejoint", left: "est parti", hostNow: "Vous êtes l'hôte maintenant", mapNext: "Carte suivante — Niveau", roomNotFound: "Salon introuvable", connecting: "Connexion…", copied: "Copié ✓", paused: "Pause", resume: "Reprendre", exit: "Quitter au menu", help: "Comment jouer", howTitle: "Comment jouer", close: "Fermer", hIdea: "L'idée", hIdeaTxt: "Mange les cubes ≤ ta tête. Égaux fusionnent (2,4,8…). Évite bords et zones rouges.", hModes: "Modes", mPublic: "Public", mPrivate: "Privé", hControls: "Commandes", hPowers: "Bonus", cSteer: "Diriger", cBoost: "Boost", cPause: "Pause", cEmoji: "Emoji", cCharge: "Charge", pSpeed: "Vitesse", pDouble: "Double", pHalf: "Moitié", pRadar: "Radar", hInstall: "Installer", hInstallTxt: "Touche l'icône du jeu en haut du menu pour l'installer. iPhone : Partager → Sur l'écran d'accueil.", shape: "Forme", hSolo: "👤 Mange les cubes dont le nombre est égal ou inférieur à ta tête pour grandir. Quand deux nombres égaux se touchent, ils fusionnent au suivant (2 devient 4, puis 8, etc.), ton serpent s'allonge et sa tête monte.", hMulti: "👥 Tu peux manger les autres joueurs pour grandir. Mords n'importe quelle partie du corps d'un rival dont le nombre est inférieur à ta tête. Si tu manges la tête du rival, il perd et quitte.", hAvoid: "Évite les bords de la carte, en sortir tue instantanément, et éloigne-toi des zones rouges dangereuses.", pSpeedTxt: "Boost de vitesse pendant 3s.", pDoubleTxt: "Double tous tes nombres.", pHalfTxt: "Divise tes nombres par deux (le 2 disparaît).", pRadarTxt: "Révèle les joueurs proches pendant 8s.", pDanger: "Danger", pDangerTxt: "Zone rouge — lâche tes cubes un par un ; s'il ne reste que la tête, tu perds.", installHint: "Ouvre le menu du navigateur → « Sur l'écran d'accueil »", netTimeout: "Impossible de joindre le serveur — vérifie ta connexion et réessaie.", netGlobal: "Mondial (Internet)", netLocal: "Local (Wi‑Fi)", netNeedInternet: "Le mode mondial nécessite une connexion internet." },

  de: { _name: "Deutsch", stats: "Deine Statistik", best: "Top", score: "Punkte", length: "Länge", time: "Zeit", high: "Rekord", level: "Stufe", leaderboard: "Bestenliste", play: "Spielen", online: "Online spielen", join: "Beitreten", joinTitle: "Mit Code beitreten", joinPh: "Code einfügen", paste: "Einfügen", install: "📲 App installieren", roomCode: "Raumcode — an Freunde senden", roomShort: "Raum", copy: "Code kopieren", gameOver: "Spiel vorbei", winner: "Gewinner", winNote: "🎁 Preis: 3 Doppel-Ladungen — tippen oder E", restart: "Neustart", solo: "Einzeln", multi: "Mehrspieler", lock: "Öffentlich / Privat", namePh: "Dein Name", you: "Du", search: "Sprache suchen…", joined: "beigetreten", left: "verlassen", hostNow: "Du bist jetzt der Host", mapNext: "Nächste Karte — Stufe", roomNotFound: "Raum nicht gefunden", connecting: "Verbinde…", copied: "Kopiert ✓", paused: "Pause", resume: "Fortsetzen", exit: "Zum Menü", help: "Anleitung", howTitle: "Anleitung", close: "Schließen", hIdea: "Die Idee", hIdeaTxt: "Iss Würfel ≤ Kopf. Gleiche verschmelzen (2,4,8…). Meide Ränder & rote Zonen.", hModes: "Modi", mPublic: "Öffentlich", mPrivate: "Privat", hControls: "Steuerung", hPowers: "Power-ups", cSteer: "Lenken", cBoost: "Boost", cPause: "Pause", cEmoji: "Emoji", cCharge: "Ladung", pSpeed: "Tempo", pDouble: "Doppelt", pHalf: "Hälfte", pRadar: "Radar", hInstall: "Installieren", hInstallTxt: "Tippe oben im Menü auf das Spielsymbol, um es zu installieren. iPhone: Teilen → Zum Home-Bildschirm.", shape: "Form", hSolo: "👤 Iss Würfel mit gleicher oder kleinerer Zahl als dein Kopf, um zu wachsen. Berühren sich zwei gleiche Zahlen, verschmelzen sie zur nächsten (2 wird 4, dann 8 usw.), deine Schlange wird länger und ihr Kopf höher.", hMulti: "👥 Du kannst andere Spieler fressen, um zu wachsen. Beiße jeden Körperteil eines Gegners, dessen Zahl kleiner als dein Kopf ist. Frisst du den Kopf des Gegners, verliert er und scheidet aus.", hAvoid: "Meide die Kartenränder – sie zu verlassen bedeutet sofortigen Tod – und halte dich von den roten Gefahrenzonen fern.", pSpeedTxt: "Tempo-Boost für 3s.", pDoubleTxt: "Verdoppelt alle deine Zahlen.", pHalfTxt: "Halbiert deine Zahlen (eine 2 verschwindet).", pRadarTxt: "Zeigt 8s lang die nächsten Spieler.", pDanger: "Gefahr", pDangerTxt: "Rote Zone — lässt deine Würfel einzeln fallen; bleibt nur der Kopf, verlierst du.", installHint: "Öffne das Browser-Menü → „Zum Home-Bildschirm“", netTimeout: "Server nicht erreichbar — prüfe dein Internet und versuche es erneut.", netGlobal: "Global (Internet)", netLocal: "Lokal (WLAN)", netNeedInternet: "Der globale Modus benötigt eine Internetverbindung." },

  pt: { _name: "Português", stats: "Suas estatísticas", best: "Máx", score: "Pontos", length: "Tamanho", time: "Tempo", high: "Recorde", level: "Fase", leaderboard: "Líderes", play: "Jogar", online: "Jogar online", join: "Entrar", joinTitle: "Entrar com código", joinPh: "Cole o código", paste: "Colar", install: "📲 Instalar app", roomCode: "Código da sala — envie aos amigos", roomShort: "Sala", copy: "Copiar código", gameOver: "Fim de jogo", winner: "Vencedor", winNote: "🎁 Prêmio: 3 cargas duplas — toque ou E", restart: "Reiniciar", solo: "Individual", multi: "Multijogador", lock: "Pública / Privada", namePh: "Seu nome", you: "Você", search: "Buscar idioma…", joined: "entrou", left: "saiu", hostNow: "Você é o anfitrião agora", mapNext: "Próximo mapa — Fase", roomNotFound: "Sala não encontrada", connecting: "Conectando…", copied: "Copiado ✓", paused: "Pausa", resume: "Retomar", exit: "Sair ao menu", help: "Como jogar", howTitle: "Como jogar", close: "Fechar", hIdea: "A ideia", hIdeaTxt: "Coma cubos ≤ sua cabeça. Iguais fundem (2,4,8…). Evite bordas e zonas vermelhas.", hModes: "Modos", mPublic: "Pública", mPrivate: "Privada", hControls: "Controles", hPowers: "Poderes", cSteer: "Dirigir", cBoost: "Impulso", cPause: "Pausa", cEmoji: "Emoji", cCharge: "Carga", pSpeed: "Velocidade", pDouble: "Dobro", pHalf: "Metade", pRadar: "Radar", hInstall: "Instalar", hInstallTxt: "Toque no ícone do jogo no topo do menu para instalá-lo. iPhone: Compartilhar → Adicionar à Tela de Início.", shape: "Forma", hSolo: "👤 Coma cubos cujo número seja igual ou menor que sua cabeça para crescer. Quando dois números iguais se tocam, fundem-se no próximo (2 vira 4, depois 8, etc.), sua cobra fica maior e a cabeça sobe.", hMulti: "👥 Você pode comer outros jogadores para crescer. Morda qualquer parte do corpo de um rival cujo número seja menor que sua cabeça. Se comer a cabeça do rival, ele perde e sai.", hAvoid: "Evite as bordas do mapa, sair é morte instantânea, e fique longe das zonas vermelhas perigosas.", pSpeedTxt: "Impulso de velocidade por 3s.", pDoubleTxt: "Dobra todos os seus números.", pHalfTxt: "Divide seus números pela metade (o 2 some).", pRadarTxt: "Revela os jogadores próximos por 8s.", pDanger: "Perigo", pDangerTxt: "Zona vermelha — solta seus cubos um a um; se sobrar só a cabeça, você perde.", installHint: "Abra o menu do navegador → \"Adicionar à Tela de Início\"", netTimeout: "Não foi possível conectar ao servidor — verifique sua internet e tente novamente.", netGlobal: "Global (Internet)", netLocal: "Local (Wi‑Fi)", netNeedInternet: "O modo global precisa de conexão à internet." },

  ru: { _name: "Русский", stats: "Статистика", best: "Макс", score: "Очки", length: "Длина", time: "Время", high: "Рекорд", level: "Этап", leaderboard: "Лидеры", play: "Играть", online: "Игра онлайн", join: "Войти", joinTitle: "Войти по коду", joinPh: "Вставьте код", paste: "Вставить", install: "📲 Установить", roomCode: "Код комнаты — друзьям", roomShort: "Комната", copy: "Копировать код", gameOver: "Игра окончена", winner: "Победитель", winNote: "🎁 Приз: 3 удвоения — нажми или E", restart: "Заново", solo: "Один", multi: "Мультиплеер", lock: "Откр. / Закр.", namePh: "Ваше имя", you: "Вы", search: "Поиск языка…", joined: "вошёл", left: "вышел", hostNow: "Теперь вы хост", mapNext: "Новая карта — Этап", roomNotFound: "Комната не найдена", connecting: "Подключение…", copied: "Скопировано ✓", paused: "Пауза", resume: "Продолжить", exit: "В меню", help: "Как играть", howTitle: "Как играть", close: "Закрыть", hIdea: "Идея", hIdeaTxt: "Ешь кубы ≤ головы. Равные сливаются (2,4,8…). Избегай краёв и красных зон.", hModes: "Режимы", mPublic: "Общая", mPrivate: "Частная", hControls: "Управление", hPowers: "Усиления", cSteer: "Поворот", cBoost: "Ускор.", cPause: "Пауза", cEmoji: "Эмодзи", cCharge: "Заряд", pSpeed: "Скорость", pDouble: "Удвоить", pHalf: "Половина", pRadar: "Радар", hInstall: "Установить", hInstallTxt: "Нажмите значок игры вверху меню, чтобы установить. iPhone: Поделиться → На экран «Домой».", shape: "Форма", hSolo: "👤 Ешьте кубы с числом меньше или равным голове, чтобы расти. Когда два одинаковых числа соприкасаются, они сливаются в следующее (2 в 4, затем 8 и т. д.), змейка удлиняется, а её голова растёт.", hMulti: "👥 Вы можете поедать других игроков, чтобы расти. Кусайте любую часть тела соперника, число которой меньше вашей головы. Съедите голову соперника — он проигрывает и выбывает.", hAvoid: "Избегайте краёв карты — выход за них мгновенная смерть — и держитесь подальше от красных опасных зон.", pSpeedTxt: "Ускорение на 3 секунды.", pDoubleTxt: "Удваивает все ваши числа.", pHalfTxt: "Делит ваши числа пополам (2 исчезает).", pRadarTxt: "Показывает ближайших игроков 8 секунд.", pDanger: "Опасность", pDangerTxt: "Красная зона — сбрасывает ваши кубы по одному; останется только голова — проигрыш.", installHint: "Откройте меню браузера → «На экран ‘Домой’»", netTimeout: "Не удалось подключиться к серверу — проверьте интернет и повторите.", netGlobal: "Глобально (интернет)", netLocal: "Локально (Wi‑Fi)", netNeedInternet: "Глобальный режим требует подключения к интернету." },

  zh: { _name: "中文", stats: "你的数据", best: "最高", score: "分数", length: "长度", time: "时间", high: "最佳", level: "关卡", leaderboard: "排行榜", play: "开始", online: "在线游戏", join: "加入", joinTitle: "用代码加入", joinPh: "粘贴房间代码", paste: "粘贴", install: "📲 安装应用", roomCode: "房间代码 — 发给好友", roomShort: "房间", copy: "复制代码", gameOver: "游戏结束", winner: "胜利者", winNote: "🎁 奖励：3 次翻倍 — 点击或按 E", restart: "重玩", solo: "单人", multi: "多人", lock: "公开 / 私人", namePh: "输入名字", you: "你", search: "搜索语言…", joined: "加入了", left: "离开了", hostNow: "你现在是房主", mapNext: "下一张地图 — 关卡", roomNotFound: "未找到房间", connecting: "连接中…", copied: "已复制 ✓", paused: "暂停", resume: "继续", exit: "返回菜单", help: "玩法", howTitle: "玩法", close: "关闭", hIdea: "玩法", hIdeaTxt: "吃≤头部的方块。相同合并(2,4,8…)。避开边界和红区。", hModes: "模式", mPublic: "公开", mPrivate: "私人", hControls: "操作", hPowers: "道具", cSteer: "转向", cBoost: "加速", cPause: "暂停", cEmoji: "表情", cCharge: "充能", pSpeed: "加速", pDouble: "翻倍", pHalf: "减半", pRadar: "雷达", hInstall: "安装", hInstallTxt: "点击菜单顶部的游戏图标即可安装。iPhone：分享 → 添加到主屏幕。", shape: "形状", hSolo: "👤 吃掉数字小于或等于你头部的方块来变大。两个相同数字相碰会合并为下一个（2 变 4，再变 8……），你的蛇变长，头部数字变高。", hMulti: "👥 你可以吃掉其他玩家来变大。可以咬对手身体上任何数字小于你头部的部分。吃掉对手的头部，对方就失败并出局。", hAvoid: "避开地图边界，出界即刻死亡，并远离红色危险区。", pSpeedTxt: "加速 3 秒。", pDoubleTxt: "所有数字翻倍。", pHalfTxt: "数字减半（2 会消失）。", pRadarTxt: "显示附近玩家 8 秒。", pDanger: "危险", pDangerTxt: "红区——逐个掉落你的方块；只剩头部时你就输了。", installHint: "打开浏览器菜单 → “添加到主屏幕”", netTimeout: "无法连接服务器——请检查网络后重试。", netGlobal: "全球（联网）", netLocal: "本地（Wi‑Fi）", netNeedInternet: "全球模式需要联网。" },

  hi: { _name: "हिन्दी", stats: "आपके आँकड़े", best: "उच्च", score: "स्कोर", length: "लंबाई", time: "समय", high: "सर्वश्रेष्ठ", level: "चरण", leaderboard: "अग्रणी", play: "खेलें", online: "ऑनलाइन खेलें", join: "शामिल हों", joinTitle: "कोड से जुड़ें", joinPh: "कोड पेस्ट करें", paste: "पेस्ट", install: "📲 ऐप इंस्टॉल करें", roomCode: "रूम कोड — दोस्तों को भेजें", roomShort: "रूम", copy: "कॉपी करें", gameOver: "खेल समाप्त", winner: "विजेता", winNote: "🎁 इनाम: 3 डबल — दबाएँ या E", restart: "फिर खेलें", solo: "एकल", multi: "मल्टीप्लेयर", lock: "सार्वजनिक / निजी", namePh: "अपना नाम", you: "आप", search: "भाषा खोजें…", joined: "शामिल हुआ", left: "चला गया", hostNow: "अब आप होस्ट हैं", mapNext: "अगला मानचित्र — चरण", roomNotFound: "रूम नहीं मिला", connecting: "कनेक्ट हो रहा…", copied: "कॉपी ✓", paused: "रुका", resume: "जारी रखें", exit: "मेनू पर जाएँ", help: "कैसे खेलें", howTitle: "कैसे खेलें", close: "बंद करें", hIdea: "विचार", hIdeaTxt: "सिर ≤ क्यूब खाएँ। समान विलीन (2,4,8…)। किनारे व लाल क्षेत्र से बचें।", hModes: "मोड", mPublic: "सार्वजनिक", mPrivate: "निजी", hControls: "नियंत्रण", hPowers: "पावर-अप", cSteer: "मोड़ें", cBoost: "बूस्ट", cPause: "रुकें", cEmoji: "इमोजी", cCharge: "चार्ज", pSpeed: "गति", pDouble: "दोगुना", pHalf: "आधा", pRadar: "रडार", hInstall: "इंस्टॉल", hInstallTxt: "इंस्टॉल करने के लिए मेनू के ऊपर गेम आइकन पर टैप करें। iPhone: शेयर → होम स्क्रीन में जोड़ें।", shape: "आकार", hSolo: "👤 बढ़ने के लिए ऐसे क्यूब खाएँ जिनका नंबर आपके सिर के बराबर या उससे छोटा हो। जब दो समान नंबर मिलते हैं तो अगले में मिल जाते हैं (2 बनकर 4, फिर 8…), आपका साँप लंबा होता है और सिर का नंबर बढ़ता है।", hMulti: "👥 बढ़ने के लिए आप दूसरे खिलाड़ियों को खा सकते हैं। प्रतिद्वंद्वी के शरीर का कोई भी हिस्सा काटें जिसका नंबर आपके सिर से छोटा हो। प्रतिद्वंद्वी का सिर खाने पर वह हारकर बाहर हो जाता है।", hAvoid: "मानचित्र के किनारों से बचें—बाहर जाना तुरंत मृत्यु है—और लाल खतरनाक क्षेत्रों से दूर रहें।", pSpeedTxt: "3 सेकंड के लिए गति बूस्ट।", pDoubleTxt: "आपके सभी नंबर दोगुने।", pHalfTxt: "नंबर आधे (2 गायब हो जाता है)।", pRadarTxt: "8 सेकंड तक पास के खिलाड़ी दिखाता है।", pDanger: "खतरा", pDangerTxt: "लाल क्षेत्र—आपके क्यूब एक-एक कर गिरते हैं; सिर्फ सिर बचे तो आप हारते हैं।", installHint: "ब्राउज़र मेनू खोलें → \"होम स्क्रीन में जोड़ें\"", netTimeout: "सर्वर से कनेक्ट नहीं हो सका—इंटरनेट जाँचें और फिर कोशिश करें।", netGlobal: "ग्लोबल (इंटरनेट)", netLocal: "लोकल (वाई‑फाई)", netNeedInternet: "ग्लोबल मोड के लिए इंटरनेट ज़रूरी है।" },

  ja: { _name: "日本語", stats: "あなたの記録", best: "最高", score: "スコア", length: "長さ", time: "時間", high: "ベスト", level: "ステージ", leaderboard: "ランキング", play: "プレイ", online: "オンライン", join: "参加", joinTitle: "コードで参加", joinPh: "コードを貼り付け", paste: "貼り付け", install: "📲 アプリを入れる", roomCode: "部屋コード — 友達へ", roomShort: "部屋", copy: "コードをコピー", gameOver: "ゲームオーバー", winner: "勝者", winNote: "🎁 報酬：2倍×3 — タップか E", restart: "もう一度", solo: "ソロ", multi: "マルチ", lock: "公開 / 非公開", namePh: "名前を入力", you: "あなた", search: "言語を検索…", joined: "参加", left: "退出", hostNow: "あなたがホストです", mapNext: "次のマップ — ステージ", roomNotFound: "部屋が見つかりません", connecting: "接続中…", copied: "コピー ✓", paused: "一時停止", resume: "再開", exit: "メニューへ", help: "遊び方", howTitle: "遊び方", close: "閉じる", hIdea: "遊び方", hIdeaTxt: "頭以下のキューブを食べる。同数は合体(2,4,8…)。端と赤地帯を避ける。", hModes: "モード", mPublic: "公開", mPrivate: "非公開", hControls: "操作", hPowers: "パワーアップ", cSteer: "旋回", cBoost: "加速", cPause: "一時停止", cEmoji: "絵文字", cCharge: "チャージ", pSpeed: "スピード", pDouble: "2倍", pHalf: "半分", pRadar: "レーダー", hInstall: "インストール", hInstallTxt: "メニュー上部のゲームアイコンをタップで導入。iPhone：共有 → ホーム画面に追加。", shape: "形", hSolo: "👤 頭と同じか小さい数のキューブを食べて成長。同じ数が触れ合うと次の数に合体（2→4→8…）、ヘビが伸びて頭の数が上がります。", hMulti: "👥 他のプレイヤーを食べて成長できます。相手の体のうち頭より小さい数の部分はどこでも噛めます。相手の頭を食べるとその人は負けて退場します。", hAvoid: "マップの端を避けてください。外に出ると即死です。赤い危険地帯にも近づかないように。", pSpeedTxt: "3秒間スピードアップ。", pDoubleTxt: "全ての数字を2倍に。", pHalfTxt: "数字を半分に（2は消える）。", pRadarTxt: "8秒間、近くのプレイヤーを表示。", pDanger: "危険", pDangerTxt: "赤い地帯 — キューブが1つずつ落ちる。頭だけになると負け。", installHint: "ブラウザのメニュー → 「ホーム画面に追加」", netTimeout: "サーバーに接続できません — ネットを確認して再試行してください。", netGlobal: "グローバル（ネット）", netLocal: "ローカル（Wi‑Fi）", netNeedInternet: "グローバルモードはネット接続が必要です。" },

  ko: { _name: "한국어", stats: "내 기록", best: "최고", score: "점수", length: "길이", time: "시간", high: "베스트", level: "단계", leaderboard: "순위", play: "플레이", online: "온라인 플레이", join: "참가", joinTitle: "코드로 참가", joinPh: "코드 붙여넣기", paste: "붙여넣기", install: "📲 앱 설치", roomCode: "방 코드 — 친구에게", roomShort: "방", copy: "코드 복사", gameOver: "게임 오버", winner: "우승자", winNote: "🎁 보상: 2배 3회 — 탭 또는 E", restart: "다시", solo: "솔로", multi: "멀티플레이", lock: "공개 / 비공개", namePh: "이름 입력", you: "당신", search: "언어 검색…", joined: "참가함", left: "나감", hostNow: "이제 당신이 호스트", mapNext: "다음 맵 — 단계", roomNotFound: "방을 찾을 수 없음", connecting: "연결 중…", copied: "복사됨 ✓", paused: "일시정지", resume: "계속", exit: "메뉴로", help: "방법", howTitle: "플레이 방법", close: "닫기", hIdea: "방법", hIdeaTxt: "머리 이하 큐브 먹기. 같은 수 합체(2,4,8…). 가장자리·빨강 구역 피하기.", hModes: "모드", mPublic: "공개", mPrivate: "비공개", hControls: "조작", hPowers: "파워업", cSteer: "조향", cBoost: "부스트", cPause: "일시정지", cEmoji: "이모지", cCharge: "충전", pSpeed: "속도", pDouble: "2배", pHalf: "절반", pRadar: "레이더", hInstall: "설치", hInstallTxt: "메뉴 상단의 게임 아이콘을 눌러 설치하세요. iPhone: 공유 → 홈 화면에 추가.", shape: "모양", hSolo: "👤 머리보다 작거나 같은 숫자의 큐브를 먹어 성장하세요. 같은 숫자가 닿으면 다음 숫자로 합쳐지고(2→4→8…), 뱀이 길어지고 머리 숫자가 올라갑니다.", hMulti: "👥 다른 플레이어를 먹어 성장할 수 있습니다. 상대 몸에서 머리보다 작은 숫자 부분은 어디든 물 수 있습니다. 상대의 머리를 먹으면 그 사람은 패배하고 나갑니다.", hAvoid: "맵 가장자리를 피하세요. 벗어나면 즉사입니다. 빨간 위험 구역도 멀리하세요.", pSpeedTxt: "3초간 속도 부스트.", pDoubleTxt: "모든 숫자를 2배로.", pHalfTxt: "숫자를 절반으로(2는 사라짐).", pRadarTxt: "8초간 가까운 플레이어 표시.", pDanger: "위험", pDangerTxt: "빨강 구역 — 큐브가 하나씩 떨어짐; 머리만 남으면 패배.", installHint: "브라우저 메뉴 → \"홈 화면에 추가\"", netTimeout: "서버에 연결할 수 없습니다 — 인터넷을 확인하고 다시 시도하세요.", netGlobal: "글로벌(인터넷)", netLocal: "로컬(Wi‑Fi)", netNeedInternet: "글로벌 모드는 인터넷이 필요합니다." },

  tr: { _name: "Türkçe", stats: "İstatistiklerin", best: "En yüksek", score: "Puan", length: "Uzunluk", time: "Süre", high: "Rekor", level: "Aşama", leaderboard: "Liderler", play: "Oyna", online: "Çevrimiçi oyna", join: "Katıl", joinTitle: "Kodla katıl", joinPh: "Kodu yapıştır", paste: "Yapıştır", install: "📲 Uygulamayı yükle", roomCode: "Oda kodu — arkadaşlarına gönder", roomShort: "Oda", copy: "Kodu kopyala", gameOver: "Oyun bitti", winner: "Kazanan", winNote: "🎁 Ödül: 3 ikiye katlama — dokun veya E", restart: "Tekrar", solo: "Tek", multi: "Çok oyunculu", lock: "Açık / Özel", namePh: "Adını yaz", you: "Sen", search: "Dil ara…", joined: "katıldı", left: "ayrıldı", hostNow: "Artık ev sahibisin", mapNext: "Sonraki harita — Aşama", roomNotFound: "Oda bulunamadı", connecting: "Bağlanıyor…", copied: "Kopyalandı ✓", paused: "Duraklat", resume: "Devam", exit: "Menüye dön", help: "Nasıl oynanır", howTitle: "Nasıl oynanır", close: "Kapat", hIdea: "Fikir", hIdeaTxt: "Kafan ≤ küpleri ye. Eşitler birleşir (2,4,8…). Kenar ve kırmızıdan kaçın.", hModes: "Modlar", mPublic: "Genel", mPrivate: "Özel", hControls: "Kontroller", hPowers: "Güçler", cSteer: "Yönlendir", cBoost: "Hızlan", cPause: "Duraklat", cEmoji: "Emoji", cCharge: "Şarj", pSpeed: "Hız", pDouble: "İki kat", pHalf: "Yarı", pRadar: "Radar", hInstall: "Yükle", hInstallTxt: "Kurmak için menünün üstündeki oyun simgesine dokun. iPhone: Paylaş → Ana Ekrana Ekle.", shape: "Şekil", hSolo: "👤 Büyümek için kafandan küçük veya eşit sayıdaki küpleri ye. İki eşit sayı dokununca bir sonrakine birleşir (2, 4 olur, sonra 8…), yılanın uzar ve kafa sayısı yükselir.", hMulti: "👥 Büyümek için diğer oyuncuları yiyebilirsin. Rakibin gövdesinde kafandan küçük olan herhangi bir parçayı ısırabilirsin. Rakibin kafasını yersen o kaybeder ve elenir.", hAvoid: "Harita kenarlarından kaçın, dışarı çıkmak anında ölümdür; kırmızı tehlike bölgelerinden uzak dur.", pSpeedTxt: "3 saniye hız artışı.", pDoubleTxt: "Tüm sayılarını ikiye katlar.", pHalfTxt: "Sayılarını yarıya böler (2 kaybolur).", pRadarTxt: "8 saniye yakındaki oyuncuları gösterir.", pDanger: "Tehlike", pDangerTxt: "Kırmızı bölge — küplerini birer birer düşürür; sadece kafa kalırsa kaybedersin.", installHint: "Tarayıcı menüsünü aç → \"Ana Ekrana Ekle\"", netTimeout: "Sunucuya ulaşılamadı — internetini kontrol edip tekrar dene.", netGlobal: "Küresel (İnternet)", netLocal: "Yerel (Wi‑Fi)", netNeedInternet: "Küresel mod internet bağlantısı gerektirir." },

  id: { _name: "Indonesia", stats: "Statistikmu", best: "Tertinggi", score: "Skor", length: "Panjang", time: "Waktu", high: "Terbaik", level: "Tahap", leaderboard: "Peringkat", play: "Main", online: "Main online", join: "Gabung", joinTitle: "Gabung dengan kode", joinPh: "Tempel kode", paste: "Tempel", install: "📲 Pasang aplikasi", roomCode: "Kode ruang — kirim ke teman", roomShort: "Ruang", copy: "Salin kode", gameOver: "Permainan selesai", winner: "Pemenang", winNote: "🎁 Hadiah: 3 ganda — ketuk atau E", restart: "Ulang", solo: "Sendiri", multi: "Multipemain", lock: "Publik / Privat", namePh: "Nama kamu", you: "Kamu", search: "Cari bahasa…", joined: "bergabung", left: "keluar", hostNow: "Kamu sekarang host", mapNext: "Peta berikutnya — Tahap", roomNotFound: "Ruang tidak ada", connecting: "Menghubungkan…", copied: "Tersalin ✓", paused: "Jeda", resume: "Lanjut", exit: "Ke menu", help: "Cara main", howTitle: "Cara main", close: "Tutup", hIdea: "Ide", hIdeaTxt: "Makan kubus ≤ kepala. Sama menyatu (2,4,8…). Hindari tepi & zona merah.", hModes: "Mode", mPublic: "Publik", mPrivate: "Privat", hControls: "Kontrol", hPowers: "Power-up", cSteer: "Arahkan", cBoost: "Dorong", cPause: "Jeda", cEmoji: "Emoji", cCharge: "Isi", pSpeed: "Cepat", pDouble: "Ganda", pHalf: "Separuh", pRadar: "Radar", hInstall: "Pasang", hInstallTxt: "Ketuk ikon game di atas menu untuk memasangnya. iPhone: Bagikan → Tambah ke Layar Utama.", shape: "Bentuk", hSolo: "👤 Makan kubus yang angkanya sama atau lebih kecil dari kepalamu untuk tumbuh. Saat dua angka sama bersentuhan, keduanya menyatu jadi angka berikutnya (2 jadi 4, lalu 8…), ularmu memanjang dan angka kepalanya naik.", hMulti: "👥 Kamu bisa memakan pemain lain untuk tumbuh. Gigit bagian tubuh lawan mana pun yang angkanya lebih kecil dari kepalamu. Jika kamu memakan kepala lawan, dia kalah dan keluar.", hAvoid: "Hindari tepi peta, keluar berarti mati seketika, dan jauhi zona merah berbahaya.", pSpeedTxt: "Dorongan kecepatan 3 detik.", pDoubleTxt: "Menggandakan semua angkamu.", pHalfTxt: "Membagi dua angkamu (angka 2 hilang).", pRadarTxt: "Menampilkan pemain terdekat 8 detik.", pDanger: "Bahaya", pDangerTxt: "Zona merah — menjatuhkan kubusmu satu per satu; jika tinggal kepala, kamu kalah.", installHint: "Buka menu peramban → \"Tambah ke Layar Utama\"", netTimeout: "Tidak bisa menghubungi server — periksa internet dan coba lagi.", netGlobal: "Global (Internet)", netLocal: "Lokal (Wi‑Fi)", netNeedInternet: "Mode global butuh koneksi internet." },

  fa: { _name: "فارسی", _rtl: 1, stats: "آمار شما", best: "بیشترین", score: "امتیاز", length: "طول", time: "زمان", high: "بهترین", level: "مرحله", leaderboard: "برترین‌ها", play: "بازی", online: "بازی آنلاین", join: "پیوستن", joinTitle: "پیوستن با کد", joinPh: "کد را بچسبانید", paste: "چسباندن", install: "📲 نصب برنامه", roomCode: "کد اتاق — برای دوستان", roomShort: "اتاق", copy: "کپی کد", gameOver: "پایان بازی", winner: "برنده", winNote: "🎁 جایزه: ۳ دوبرابر — بزن یا E", restart: "از نو", solo: "تک‌نفره", multi: "چندنفره", lock: "عمومی / خصوصی", namePh: "نامت را بنویس", you: "شما", search: "جستجوی زبان…", joined: "پیوست", left: "خارج شد", hostNow: "اکنون میزبان شمایید", mapNext: "نقشه بعدی — مرحله", roomNotFound: "اتاق پیدا نشد", connecting: "در حال اتصال…", copied: "کپی شد ✓", paused: "توقف", resume: "ادامه", exit: "به منو", help: "راهنما", howTitle: "راهنمای بازی", close: "بستن", hIdea: "ایده", hIdeaTxt: "مکعب‌های ≤ سر را بخور. مساوی‌ها ادغام (۲،۴،۸…). از لبه و مناطق قرمز دوری کن.", hModes: "حالت‌ها", mPublic: "عمومی", mPrivate: "خصوصی", hControls: "کنترل", hPowers: "قدرت‌ها", cSteer: "هدایت", cBoost: "شتاب", cPause: "توقف", cEmoji: "ایموجی", cCharge: "شارژ", pSpeed: "سرعت", pDouble: "دوبرابر", pHalf: "نصف", pRadar: "رادار", hInstall: "نصب", hInstallTxt: "برای نصب روی آیکن بازی در بالای منو بزن. آیفون: اشتراک ← افزودن به صفحه اصلی.", shape: "شکل", hSolo: "👤 برای بزرگ‌شدن مکعب‌هایی را بخور که عددشان مساوی یا کوچک‌تر از سرت است. وقتی دو عدد مساوی به هم برسند در عدد بعدی ادغام می‌شوند (۲ می‌شود ۴، سپس ۸…)، مارت بلندتر می‌شود و عدد سرش بالا می‌رود.", hMulti: "👥 می‌توانی برای بزرگ‌شدن بازیکنان دیگر را بخوری. هر بخشی از بدن حریف را که عددش کوچک‌تر از سرت باشد می‌توانی گاز بگیری. اگر سر حریف را بخوری، او می‌بازد و خارج می‌شود.", hAvoid: "از لبه‌های نقشه دوری کن، خروج یعنی مرگ فوری، و از مناطق قرمز خطرناک فاصله بگیر.", pSpeedTxt: "شتاب سرعت برای ۳ ثانیه.", pDoubleTxt: "همه اعدادت را دو برابر می‌کند.", pHalfTxt: "اعدادت را نصف می‌کند (۲ ناپدید می‌شود).", pRadarTxt: "بازیکنان نزدیک را ۸ ثانیه نشان می‌دهد.", pDanger: "خطر", pDangerTxt: "منطقه قرمز — مکعب‌هایت را یکی‌یکی می‌اندازد؛ اگر فقط سر بماند می‌بازی.", installHint: "منوی مرورگر را باز کن ← «افزودن به صفحه اصلی»", netTimeout: "اتصال به سرور ممکن نشد — اینترنت را بررسی کن و دوباره تلاش کن.", netGlobal: "جهانی (اینترنت)", netLocal: "محلی (وای‑فای)", netNeedInternet: "حالت جهانی به اینترنت نیاز دارد." },

  ur: { _name: "اردو", _rtl: 1, stats: "آپ کے اعداد", best: "زیادہ", score: "اسکور", length: "لمبائی", time: "وقت", high: "بہترین", level: "مرحلہ", leaderboard: "سرفہرست", play: "کھیلیں", online: "آن لائن کھیلیں", join: "شامل ہوں", joinTitle: "کوڈ سے شامل ہوں", joinPh: "کوڈ پیسٹ کریں", paste: "پیسٹ", install: "📲 ایپ انسٹال کریں", roomCode: "روم کوڈ — دوستوں کو بھیجیں", roomShort: "روم", copy: "کوڈ کاپی", gameOver: "کھیل ختم", winner: "فاتح", winNote: "🎁 انعام: 3 ڈبل — دبائیں یا E", restart: "دوبارہ", solo: "اکیلے", multi: "ملٹی پلیئر", lock: "عوامی / نجی", namePh: "اپنا نام لکھیں", you: "آپ", search: "زبان تلاش کریں…", joined: "شامل ہوا", left: "چلا گیا", hostNow: "اب آپ میزبان ہیں", mapNext: "اگلا نقشہ — مرحلہ", roomNotFound: "روم نہیں ملا", connecting: "جڑ رہا ہے…", copied: "کاپی ✓", paused: "وقفہ", resume: "جاری رکھیں", exit: "مینو پر", help: "طریقہ", howTitle: "کھیلنے کا طریقہ", close: "بند کریں", hIdea: "خیال", hIdeaTxt: "سر ≤ کیوب کھائیں۔ برابر ضم (2,4,8…)۔ کناروں و سرخ زون سے بچیں۔", hModes: "موڈز", mPublic: "عوامی", mPrivate: "نجی", hControls: "کنٹرول", hPowers: "پاورز", cSteer: "رخ", cBoost: "بوسٹ", cPause: "وقفہ", cEmoji: "ایموجی", cCharge: "چارج", pSpeed: "رفتار", pDouble: "دگنا", pHalf: "نصف", pRadar: "ریڈار", hInstall: "انسٹال", hInstallTxt: "انسٹال کے لیے مینو کے اوپر گیم آئیکن پر ٹیپ کریں۔ iPhone: شیئر ← ہوم اسکرین میں شامل کریں۔", shape: "شکل", hSolo: "👤 بڑھنے کے لیے ایسے کیوب کھائیں جن کا نمبر آپ کے سر کے برابر یا اس سے چھوٹا ہو۔ جب دو برابر نمبر چھوتے ہیں تو اگلے میں ضم ہو جاتے ہیں (2 بن کر 4، پھر 8…)، آپ کا سانپ لمبا ہوتا ہے اور سر کا نمبر بڑھتا ہے۔", hMulti: "👥 بڑھنے کے لیے آپ دوسرے کھلاڑیوں کو کھا سکتے ہیں۔ حریف کے جسم کا کوئی بھی حصہ کاٹیں جس کا نمبر آپ کے سر سے چھوٹا ہو۔ حریف کا سر کھانے پر وہ ہار کر باہر ہو جاتا ہے۔", hAvoid: "نقشے کے کناروں سے بچیں، باہر جانا فوری موت ہے، اور سرخ خطرناک علاقوں سے دور رہیں۔", pSpeedTxt: "3 سیکنڈ رفتار بوسٹ۔", pDoubleTxt: "آپ کے تمام نمبر دگنے۔", pHalfTxt: "نمبر آدھے (2 غائب ہو جاتا ہے)۔", pRadarTxt: "8 سیکنڈ قریبی کھلاڑی دکھاتا ہے۔", pDanger: "خطرہ", pDangerTxt: "سرخ علاقہ — آپ کے کیوب ایک ایک کر گرتے ہیں؛ صرف سر بچے تو آپ ہار جاتے ہیں۔", installHint: "براؤزر مینو کھولیں ← \"ہوم اسکرین میں شامل کریں\"", netTimeout: "سرور سے رابطہ نہ ہوسکا — انٹرنیٹ چیک کریں اور دوبارہ کوشش کریں۔", netGlobal: "گلوبل (انٹرنیٹ)", netLocal: "لوکل (وائی‑فائی)", netNeedInternet: "گلوبل موڈ کے لیے انٹرنیٹ ضروری ہے۔" },

  it: { _name: "Italiano", stats: "Le tue statistiche", best: "Max", score: "Punti", length: "Lunghezza", time: "Tempo", high: "Record", level: "Livello", leaderboard: "Classifica", play: "Gioca", online: "Gioca online", join: "Unisciti", joinTitle: "Unisciti con codice", joinPh: "Incolla il codice", paste: "Incolla", install: "📲 Installa app", roomCode: "Codice stanza — agli amici", roomShort: "Stanza", copy: "Copia codice", gameOver: "Game Over", winner: "Vincitore", winNote: "🎁 Premio: 3 raddoppi — tocca o E", restart: "Rigioca", solo: "Singolo", multi: "Multigiocatore", lock: "Pubblica / Privata", namePh: "Il tuo nome", you: "Tu", search: "Cerca lingua…", joined: "è entrato", left: "è uscito", hostNow: "Ora sei l'host", mapNext: "Mappa successiva — Livello", roomNotFound: "Stanza non trovata", connecting: "Connessione…", copied: "Copiato ✓", paused: "Pausa", resume: "Riprendi", exit: "Esci al menu", help: "Come giocare", howTitle: "Come giocare", close: "Chiudi", hIdea: "L'idea", hIdeaTxt: "Mangia cubi ≤ testa. Uguali si fondono (2,4,8…). Evita bordi e zone rosse.", hModes: "Modalità", mPublic: "Pubblica", mPrivate: "Privata", hControls: "Comandi", hPowers: "Potenziamenti", cSteer: "Sterza", cBoost: "Spinta", cPause: "Pausa", cEmoji: "Emoji", cCharge: "Carica", pSpeed: "Velocità", pDouble: "Doppio", pHalf: "Metà", pRadar: "Radar", hInstall: "Installa", hInstallTxt: "Tocca l'icona del gioco in cima al menu per installarlo. iPhone: Condividi → Aggiungi a Home.", shape: "Forma", hSolo: "👤 Mangia i cubi con numero uguale o minore della tua testa per crescere. Quando due numeri uguali si toccano si fondono nel successivo (2 diventa 4, poi 8, ecc.), il serpente si allunga e la testa sale.", hMulti: "👥 Puoi mangiare gli altri giocatori per crescere. Mordi qualsiasi parte del corpo di un rivale con numero minore della tua testa. Se mangi la testa del rivale, quel giocatore perde ed esce.", hAvoid: "Evita i bordi della mappa, uscire è morte istantanea, e stai lontano dalle zone rosse pericolose.", pSpeedTxt: "Spinta di velocità per 3s.", pDoubleTxt: "Raddoppia tutti i tuoi numeri.", pHalfTxt: "Dimezza i tuoi numeri (il 2 sparisce).", pRadarTxt: "Mostra i giocatori vicini per 8s.", pDanger: "Pericolo", pDangerTxt: "Zona rossa — fa cadere i tuoi cubi uno a uno; se resta solo la testa, perdi.", installHint: "Apri il menu del browser → \"Aggiungi a Home\"", netTimeout: "Impossibile raggiungere il server — controlla la connessione e riprova.", netGlobal: "Globale (Internet)", netLocal: "Locale (Wi‑Fi)", netNeedInternet: "La modalità globale richiede una connessione internet." },
};

// قائمة لغات للبحث (الاسم المحلي + الإنجليزي + كلمات بحث/دول).
window.LANGS = [
  { code: "en", native: "English", en: "English", q: "english usa uk en" },
  { code: "ar", native: "العربية", en: "Arabic", q: "arabic عربي السعودية مصر" },
  { code: "es", native: "Español", en: "Spanish", q: "spanish espanol mexico spain" },
  { code: "fr", native: "Français", en: "French", q: "french france francais" },
  { code: "de", native: "Deutsch", en: "German", q: "german deutschland germany" },
  { code: "pt", native: "Português", en: "Portuguese", q: "portuguese brasil portugal" },
  { code: "ru", native: "Русский", en: "Russian", q: "russian russia" },
  { code: "zh", native: "中文", en: "Chinese", q: "chinese china mandarin 中文" },
  { code: "hi", native: "हिन्दी", en: "Hindi", q: "hindi india" },
  { code: "ja", native: "日本語", en: "Japanese", q: "japanese japan 日本" },
  { code: "ko", native: "한국어", en: "Korean", q: "korean korea 한국" },
  { code: "tr", native: "Türkçe", en: "Turkish", q: "turkish turkey turkiye" },
  { code: "id", native: "Indonesia", en: "Indonesian", q: "indonesian indonesia" },
  { code: "fa", native: "فارسی", en: "Persian", q: "persian farsi iran" },
  { code: "ur", native: "اردو", en: "Urdu", q: "urdu pakistan" },
  { code: "it", native: "Italiano", en: "Italian", q: "italian italy italia" },
  { code: "bn", native: "বাংলা", en: "Bengali", q: "bengali bangladesh" },
  { code: "pa", native: "ਪੰਜਾਬੀ", en: "Punjabi", q: "punjabi" },
  { code: "vi", native: "Tiếng Việt", en: "Vietnamese", q: "vietnamese vietnam" },
  { code: "th", native: "ไทย", en: "Thai", q: "thai thailand" },
  { code: "nl", native: "Nederlands", en: "Dutch", q: "dutch netherlands" },
  { code: "pl", native: "Polski", en: "Polish", q: "polish poland" },
  { code: "uk", native: "Українська", en: "Ukrainian", q: "ukrainian ukraine" },
  { code: "ro", native: "Română", en: "Romanian", q: "romanian romania" },
  { code: "el", native: "Ελληνικά", en: "Greek", q: "greek greece" },
  { code: "sv", native: "Svenska", en: "Swedish", q: "swedish sweden" },
  { code: "cs", native: "Čeština", en: "Czech", q: "czech" },
  { code: "hu", native: "Magyar", en: "Hungarian", q: "hungarian hungary" },
  { code: "he", native: "עברית", en: "Hebrew", q: "hebrew israel", rtl: 1 },
  { code: "ms", native: "Melayu", en: "Malay", q: "malay malaysia" },
  { code: "fil", native: "Filipino", en: "Filipino", q: "filipino tagalog philippines" },
  { code: "sw", native: "Kiswahili", en: "Swahili", q: "swahili kenya tanzania" },
  { code: "ta", native: "தமிழ்", en: "Tamil", q: "tamil" },
  { code: "te", native: "తెలుగు", en: "Telugu", q: "telugu" },
  { code: "mr", native: "मराठी", en: "Marathi", q: "marathi" },
  { code: "gu", native: "ગુજરાતી", en: "Gujarati", q: "gujarati" },
  { code: "kn", native: "ಕನ್ನಡ", en: "Kannada", q: "kannada" },
  { code: "ml", native: "മലയാളം", en: "Malayalam", q: "malayalam" },
  { code: "ha", native: "Hausa", en: "Hausa", q: "hausa nigeria" },
  { code: "am", native: "አማርኛ", en: "Amharic", q: "amharic ethiopia" },
  { code: "az", native: "Azərbaycan", en: "Azerbaijani", q: "azerbaijani" },
  { code: "uz", native: "Oʻzbek", en: "Uzbek", q: "uzbek" },
  { code: "kk", native: "Қазақ", en: "Kazakh", q: "kazakh" },
  { code: "bg", native: "Български", en: "Bulgarian", q: "bulgarian" },
  { code: "sr", native: "Српски", en: "Serbian", q: "serbian serbia" },
  { code: "hr", native: "Hrvatski", en: "Croatian", q: "croatian croatia" },
  { code: "sk", native: "Slovenčina", en: "Slovak", q: "slovak" },
  { code: "da", native: "Dansk", en: "Danish", q: "danish denmark" },
  { code: "fi", native: "Suomi", en: "Finnish", q: "finnish finland" },
  { code: "no", native: "Norsk", en: "Norwegian", q: "norwegian norway" },
];
